server:
  port: 28000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
        - id: ai-service 
          uri: lb://ai-service 
          predicates:
            - Path=/ai/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**
      discovery:
        locator:
          enabled: true
